---
kind: pipeline
name: default

steps:
- name: lint
  image: maxkratz/python-custom:3.6
  commands:
  - pylint-fail-under --fail_under 9.0 -d pep8 matrix_synapse_saml_mapper/*.py setup.py

- name: build
  image: maxkratz/python-custom:3.6
  commands:
  - python setup.py sdist bdist_wheel
  depends_on:
  - lint

- name: test
  image: maxkratz/python-custom:3.6
  commands:
  - python setup.py install
  depends_on:
  - build
