---
kind: pipeline
name: default

steps:
- name: lint
  image: python:3.6
  commands:
  - &setup pip install -r requirements.txt
  - pylint --fail-under=9.0 -d pep8 matrix_synapse_saml_mapper/*.py setup.py

- name: build
  image: python:3.6
  commands:
  - *setup
  - python setup.py sdist bdist_wheel
  depends_on:
  - lint

- name: test
  image: python:3.6
  commands:
  - *setup
  - python setup.py install
  depends_on:
  - build
