stages:
    - lint
    - build
    - test

default:
    image: python:3.6

before_script:
    - python --version
    - pip install -r requirements.txt

pylint:
    stage: lint
    script:
        - pylint-fail-under --fail_under 7.0 -d pep8 dlz_saml/*.py

build:
    stage: build
    script:
        - python setup.py sdist bdist_wheel
    artifacts:
        name: "$CI_JOB_NAME"
        when: always
        paths:
            - build
            - dist
            - dlz_saml.egg-info

install:
    stage: test
    script:
        - python setup.py install
