stages:
    - lint
    - build
    - test

default:
    image: maxkratz/python-custom:3.6

pylint:
    stage: lint
    script:
        - pylint-fail-under --fail_under 9.0 -d pep8 matrix_synapse_saml_mapper/*.py setup.py

build:
    stage: build
    script:
        - python setup.py sdist bdist_wheel
    artifacts:
        name: "$CI_JOB_NAME"
        when: always
        paths:
            - build
            - dist
            - matrix_synapse_saml_mapper.egg-info

install:
    stage: test
    script:
        - python setup.py install
